name: Publish docker image
on:
  release:
    types: [published]
jobs:
  rebuild_python_image:
    name: Push image to dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        distribution: ["", "-slim", "-alpine"]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: my-docker-hub-namespace/my-docker-hub-repository

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          build-args: TAG=${{ matrix.version }}${{ matrix.distribution }}
          context: .
          push: true
          tags: ${{ matrix.version }}${{ matrix.distribution }}
