name: Create release
on:
  push:
    paths:
      - 'pdm-version.txt'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Read tag file
      id: pdm-tag
      uses: juliangruber/read-file-action@v1
      with:
        path: pdm-version.txt

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        tag: "${{ steps.pdm-tag.outputs.content }}"
