name: Check original pdm release
on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/pdm-project/pdm/releases/latest | \
          jq -r ".tag_name" > pdm-version.txt

      - name: Check for modified files
        id: git-check
        run: echo 'new_version=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")' >> $GITHUB_OUTPUT

      - name: Commit latest release version
        if: ${{ steps.git-check.outputs.new_version }} == 'true'
        run: |
          git config --global user.name 'Semyon Dubrovin'
          git config --global user.email 'seven45@mail.ru'
          git add pdm-version.txt
          git commit -am "New pdm version: $(cat pdm-version.txt)"
          git push

      - name: Create release
        if: ${{ steps.git-check.outputs.new_version }} == 'true'
        uses: ncipollo/release-action@v1
        with:
          tag: $(cat pdm-version.txt)
