name: Check new release from original pdm-repo
on:
  schedule:
    - cron:  '0 12 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/pdm-project/pdm/releases/latest | \
          jq -r ".tag_name" > Version.txt
      - name: Check for modified files
        id: git-check
        run: echo 'new_version=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")' >> $GITHUB_STATE
      - name: Commit latest release version
        if: steps.git-check.outputs.new_version == 'true'
        run: |
          git config --global user.name 'Semyon Dubrovin'
          git config --global user.email 'seven45@mail.ru'
          git add Version.txt
          git commit -am "New pdm version: $(cat Version.txt)"
          git push
