name: Publish image to dockerhub
on:
  release:
    types: [created]
jobs:
  rebuild_python_image:
    name: Push image to dockerhub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base_tag: ["3.7", "3.7-slim", "3.7-alpine", "3.8", "3.8-slim", "3.8-alpine", "3.9", "3.9-slim", "3.9-alpine", "3.10", "3.10-slim", "3.10-alpine", "3.11", "3.11-slim", "3.11-alpine"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: PYTHON_VERSION=${{ matrix.base_tag }}
          push: true
          tags: seven45/pdm-ci:${{ matrix.base_tag }}
